name: Trigger test odoo 14

on:
  push:
    branches:
      - "14.0"

jobs:
  trigger:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger event on frepple repository
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.COMMUNITY_GITHUB_TOKEN }}
          repo: frepple
          owner: frePPLe
          event_type: odoo_connector
          message: |
            {
            "branch": "14.0"
            }
